const express = require('express')
const app = express()
const path = require('path')
const bodyParser = require('body-parser')
const adminRoutes=require('./routes/admin')
const shopRoutes=require('./routes/shop')
const contactRoute=require('./routes/contact')
app.use(bodyParser.urlencoded({ extended:false }))
app.use(express.static(path.join(__dirname, 'public')))
app.use('/admin', adminRoutes)
app.use(contactRoute)
app.use(shopRoutes)
app.use((req,res)=>{
    res.status(404)
    res.send('404 Not Found')
})

app.listen(4000)